server:
  port: 8087

#激活测试环境写dev,生产环境写product
#多数据源的切换,当然也可以用其他名称,
#不一定是dev《application-dev.yml》和product《application-product.yml》
spring:
  profiles:
    active:
    - product
    
  mail:
    host: smtp.freemypal.com
    username: mq@freemypal.com
    port: 25
    password: 361minqing
    default-encoding: UTF-8
    properties:
              mail.smtp.socketFactory.fallback: true
              mail.smtp.starttls.enable: true
         
 